-- MySQL Script generated by MySQL Workbench
-- Sat Sep 13 19:11:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema terminalautomotriz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema terminalautomotriz
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `terminalautomotriz` DEFAULT CHARACTER SET utf8 ;
USE `terminalautomotriz` ;

-- -----------------------------------------------------
-- Table `terminalautomotriz`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_modelo`))
ENGINE = InnoDB;

/*
-- -----------------------------------------------------
-- Table `terminalautomotriz`.`linea_de_montaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`linea_de_montaje` (
  `id_linea_de_montaje` INT NOT NULL AUTO_INCREMENT,
  `modelo_id_modelo` INT NOT NULL UNIQUE,
  `capacidad_productiva` INT NOT NULL,
  PRIMARY KEY (`id_linea_de_montaje`),
  INDEX `fk_linea_de_montaje_modelo1_idx` (`modelo_id_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_linea_de_montaje_modelo1`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `terminalautomotriz`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

*/

-- -----------------------------------------------------
-- Table `terminalautomotriz`.`linea_de_montaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`linea_de_montaje` (
  `modelo_id_modelo` INT NOT NULL,
  `capacidad_productiva` INT NOT NULL,
  PRIMARY KEY (`modelo_id_modelo`),
  CONSTRAINT `fk_linea_de_montaje_modelo1`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `terminalautomotriz`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `terminalautomotriz`.`concesionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`concesionario` (
  `id_concesionario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id_concesionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalautomotriz`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`pedido` (
  `numero` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `concesionario_id_concesionario` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_pedido_concesionario1_idx` (`concesionario_id_concesionario` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_concesionario1`
    FOREIGN KEY (`concesionario_id_concesionario`)
    REFERENCES `terminalautomotriz`.`concesionario` (`id_concesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalautomotriz`.`detalle_del_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`detalle_del_pedido` (
  `cantidad` INT NOT NULL,
  `pedido_numero` INT NOT NULL,
  `modelo_id_modelo` INT NOT NULL,
  PRIMARY KEY (`pedido_numero`, `modelo_id_modelo`),
  INDEX `fk_detalle_del_pedido_pedido1_idx` (`pedido_numero` ASC) VISIBLE,
  INDEX `fk_detalle_del_pedido_modelo1_idx` (`modelo_id_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_del_pedido_pedido1`
    FOREIGN KEY (`pedido_numero`)
    REFERENCES `terminalautomotriz`.`pedido` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_del_pedido_modelo1`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `terminalautomotriz`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalautomotriz`.`automovil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`automovil` (
  `numero_de_chasis` VARCHAR(45) NOT NULL,
  `patente` VARCHAR(45) NOT NULL,
  `fecha_finalizacion` DATETIME NULL,
  `pedido_numero` INT NOT NULL,
  `modelo_id_modelo` INT NOT NULL,
  PRIMARY KEY (`numero_de_chasis`),
  INDEX `fk_automovil_pedido1_idx` (`pedido_numero` ASC) VISIBLE,
  INDEX `fk_automovil_modelo1_idx` (`modelo_id_modelo` ASC) VISIBLE,
  UNIQUE INDEX `patente_UNIQUE` (`patente` ASC) VISIBLE,
  CONSTRAINT `fk_automovil_pedido1`
    FOREIGN KEY (`pedido_numero`)
    REFERENCES `terminalautomotriz`.`pedido` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_automovil_modelo1`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `terminalautomotriz`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalautomotriz`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`tarea` (
  `id_tarea` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tarea`))
ENGINE = InnoDB;

/*
-- -----------------------------------------------------
-- Table `terminalautomotriz`.`estacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`estacion` (
  `id_estacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `linea_de_montaje_id_linea_de_montaje` INT NOT NULL,
  `tarea_id_tarea` INT NOT NULL,
  PRIMARY KEY (`id_estacion`),
  INDEX `fk_estacion_linea_de_montaje1_idx` (`linea_de_montaje_id_linea_de_montaje` ASC) VISIBLE,
  INDEX `fk_estacion_tarea1_idx` (`tarea_id_tarea` ASC) VISIBLE,
  CONSTRAINT `fk_estacion_linea_de_montaje1`
    FOREIGN KEY (`linea_de_montaje_id_linea_de_montaje`)
    REFERENCES `terminalautomotriz`.`linea_de_montaje` (`id_linea_de_montaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_tarea1`
    FOREIGN KEY (`tarea_id_tarea`)
    REFERENCES `terminalautomotriz`.`tarea` (`id_tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
*/
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`estacion` (
  `id_estacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `modelo_id_modelo` INT NOT NULL,
  `tarea_id_tarea` INT NOT NULL,
  PRIMARY KEY (`id_estacion`),
  INDEX `fk_estacion_modelo_idx` (`modelo_id_modelo` ASC) VISIBLE,
  INDEX `fk_estacion_tarea_idx` (`tarea_id_tarea` ASC) VISIBLE,
  CONSTRAINT `fk_estacion_modelo`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `terminalautomotriz`.`linea_de_montaje` (`modelo_id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_tarea`
    FOREIGN KEY (`tarea_id_tarea`)
    REFERENCES `terminalautomotriz`.`tarea` (`id_tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `terminalautomotriz`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`insumo` (
  `codigo_insumo` INT NOT NULL,
  `precio_insumo` INT NOT NULL,
  `descripcion_insumo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_insumo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `terminalautomotriz`.`tarea_CON_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`tarea_CON_insumo` (
  `cantidad` FLOAT NOT NULL,
  `tarea_id_tarea` INT NOT NULL,
  `insumo_codigo_insumo` INT NOT NULL,
  PRIMARY KEY (`tarea_id_tarea`, `insumo_codigo_insumo`),
  INDEX `fk_tarea_CON_insumo_insumo1_idx` (`insumo_codigo_insumo` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_CON_insumo_tarea1`
    FOREIGN KEY (`tarea_id_tarea`)
    REFERENCES `terminalautomotriz`.`tarea` (`id_tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_CON_insumo_insumo1`
    FOREIGN KEY (`insumo_codigo_insumo`)
    REFERENCES `terminalautomotriz`.`insumo` (`codigo_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalautomotriz`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`proveedor` (
  `id_proveedor` INT NOT NULL,
  `nombre_proveedor` VARCHAR(45) NOT NULL,
  `direccion_proveedor` VARCHAR(45) NOT NULL,
  `telefono_proveedor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalautomotriz`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`compra` (
  `numero_compra` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `proveedor_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`numero_compra`),
  INDEX `fk_compra_proveedor1_idx` (`proveedor_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_compra_proveedor1`
    FOREIGN KEY (`proveedor_id_proveedor`)
    REFERENCES `terminalautomotriz`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalautomotriz`.`detalle_compra_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`detalle_compra_insumo` (
  `precio` FLOAT NOT NULL,
  `cantidad` INT NOT NULL,
  `insumo_codigo_insumo` INT NOT NULL,
  `compra_numero_compra` INT NOT NULL,
  PRIMARY KEY (`insumo_codigo_insumo`, `compra_numero_compra`),
  INDEX `fk_detalle_compra_insumo_compra1_idx` (`compra_numero_compra` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_compra_insumo_insumo1`
    FOREIGN KEY (`insumo_codigo_insumo`)
    REFERENCES `terminalautomotriz`.`insumo` (`codigo_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_compra_insumo_compra1`
    FOREIGN KEY (`compra_numero_compra`)
    REFERENCES `terminalautomotriz`.`compra` (`numero_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalautomotriz`.`historial_produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`historial_produccion` (
  `automovil_numero_de_chasis` VARCHAR(45) NOT NULL,
  `estacion_id_estacion` INT NOT NULL,
  `fecha_hora_ingreso` DATETIME NOT NULL,
  `fecha_hora_egreso` DATETIME NULL,
  PRIMARY KEY (`automovil_numero_de_chasis`, `estacion_id_estacion`),
  INDEX `fk_historial_produccion_automovil1_idx` (`automovil_numero_de_chasis` ASC) VISIBLE,
  INDEX `fk_historial_produccion_estacion1_idx` (`estacion_id_estacion` ASC) VISIBLE,
  CONSTRAINT `fk_historial_produccion_automovil1`
    FOREIGN KEY (`automovil_numero_de_chasis`)
    REFERENCES `terminalautomotriz`.`automovil` (`numero_de_chasis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_produccion_estacion1`
    FOREIGN KEY (`estacion_id_estacion`)
    REFERENCES `terminalautomotriz`.`estacion` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `terminalautomotriz`.`insumo_por_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`insumo_por_modelo` (
  `modelo_id_modelo` INT NOT NULL,
  `insumo_codigo_insumo` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  PRIMARY KEY (`modelo_id_modelo`, `insumo_codigo_insumo`),
  INDEX `fk_insumo_por_modelo_modelo1_idx` (`modelo_id_modelo` ASC) VISIBLE,
  INDEX `fk_insumo_por_modelo_insumo1_idx` (`insumo_codigo_insumo` ASC) VISIBLE,
  CONSTRAINT `fk_insumo_por_modelo_modelo1`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `terminalautomotriz`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insumo_por_modelo_insumo1`
    FOREIGN KEY (`insumo_codigo_insumo`)
    REFERENCES `terminalautomotriz`.`insumo` (`codigo_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `terminalautomotriz`.`proveedor_suministra_insumo`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `terminalautomotriz`.`proveedor_suministra_insumo` (
  `proveedor_id_proveedor` INT NOT NULL,
  `insumo_codigo_insumo` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`proveedor_id_proveedor`, `insumo_codigo_insumo`),
  INDEX `fk_proveedor_suministra_insumo_proveedor1_idx` (`proveedor_id_proveedor` ASC) VISIBLE,
  INDEX `fk_proveedor_suministra_insumo_insumo1_idx` (`insumo_codigo_insumo` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_suministra_insumo_proveedor1`
    FOREIGN KEY (`proveedor_id_proveedor`)
    REFERENCES `terminalautomotriz`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_suministra_insumo_insumo1`
    FOREIGN KEY (`insumo_codigo_insumo`)
    REFERENCES `terminalautomotriz`.`insumo` (`codigo_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;